services:
  - type: web
    name: telegram-join-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: 8793285062:AAEI9e9BB5rRe9RTrNhYRlME8DdPjs-ND9I
      - key: CHANNEL_LINK
        value: https://t.me/taj7onway
